# This file was generated by GoReleaser. DO NOT EDIT.
class Badwolf < Formula
  desc ""
  homepage ""
  url "https://github.com/marcelocorreia/badwolf/marcelocorreia/badwolf/releases/download/0.0.2/badwolf-0.0.2-darwin-x86_64.tar.gz"
  version "0.0.2"
  sha256 "29b7abc75cb1e9f60cf53f9ad18274050665020439dda07b18129b97ac54214d"

  def install
    bin.install "badwolf"
  end
end
